// 前端相关/手写代码/Vue/vuex-test/src/App.vue
<template>
  <div id="app">
    <my-Addition />
    -----------------------
    <my-Substraction />
  </div>
</template>
<script>
import Addition from './components/Addition'
import Substraction from './components/Subtraction'

export default {
  name: 'App',
  data () {
    return {}
  },
  components: {
    'my-Addition': Addition,
    'my-Substraction': Substraction
  }
}
</script>

// sources/hello-react-hoc/src/App.js
import React, { Component } from 'react';
import './App.css';
import B from './components/B';
import C from './components/C';
import E from './components/E';
import F from './components/F';
class App extends Component {
  render() {
    return (
      <div className="App">
        hello
        {/* <B name="lisi" age={22} />
        <C /> */}
        <E />
        <F />
      </div>
    );
  }
}

export default App;
